server:
  port: 5002

spring:
  mongodb:
  application:
    name: rabbitmq-consumer
  #  rabbitmq配置
  rabbitmq:
    username: user
    password: password
    host: 129.211.113.218
    port: 5672
    ###开启消息确认机制 confirms
    virtual-host: /
    publisher-confirms: true
    publisher-returns: true
    #采用手动应答
    listener:
      simple:
        acknowledge-mode: manual
        concurrency: 3
        max-concurrency: 10
    template:
      reply-timeout: 6000
      receive-timeout: 6000
  #redis配置
  redis:
    host: 129.211.113.218
    port: 6379
    database: 0
    timeout: 1000
  #mongoDb
  data:
    mongodb:
      uri: "mongodb://129.211.113.218:27017/rabbitmq"

eureka:
  instance:
    prefer-ip-address: true
    status-page-url: http://129.211.113.218:${server.port}/swagger-ui.html
  leaseRenewalIntervalInSeconds: 10
  client:
    fetch-registry: true
    registerWithEureka: true
    serviceUrl.defaultZone: http://129.211.113.218:5000/eureka/
